---
# @action Installs SDKMAN
# Ensures SDKMAN is installed on macOS and Linux systems
- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: 'install-{{ ansible_os_family }}.yml'
  when: ansible_os_family != 'Windows'
